scene: ""
skip_grid: false
skip_save: false
ddim_steps: 50
plms: false
dpm_solver: false
laion400m: false
fixed_code: false
ddim_eta: 0.0
n_iter: 1
H: 512
W: 512
C: 4
f: 8
n_samples: 1
n_rows: 0
scale: 7.5
from_file: false
precision: "autocast"